### ISSUE TITLE
Wrong description for `500` status code

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/openapi-tools#1164]
When generated the OpenAPI schema for the below.
https://github.com/shafreenAnfar/springboot-and-ballerina/tree/main/ballerina-user-rest-service

I get the below

```yaml
"500":
    description: Found unexpected output
    content:
      text/plain:
        schema:
          type: string
```
It should be

```yaml
"500":
    description: Internal server error
    content:
      text/plain:
        schema:
          type: string
```
