### ISSUE TITLE
Invalid type generation for nullabe:true object types in OpenAPI spec

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1227]
**Description:**
$subject

**Sample OpenAPI schema**

```yaml
details:
      type: object
      nullable: true
```

**Generated type**

```record{} details```

**Expected type**

```record{}? details```
