### ISSUE TITLE
Invalid record is generated when `double` type `additionalProperties` has defined

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1285]
**Description:**
$subject

Affected connectors : [googleapis.bigquery](https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.bigquery)

### Sample OpenAPI schema property

```yaml
labelClassWeights:
          additionalProperties:
            format: double
            type: number
          type: object
```

### Generated bal type
```bal
record {|double...;|} labelClassWeights?;
```

Gives the error 
`ERROR [types.bal:(470:14,470:20)] unknown type 'double'`

**Steps to reproduce:**

**Affected Versions:**
2201.4.1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
