### ISSUE TITLE
Constraint annotation doesn't  generate for the client generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1292]
**Description:**
If this yaml content includes valid constrain it doesn't generate constraint annotation for the field.
- https://github.com/ballerina-platform/openapi-connectors/blob/main/openapi/siemens.platformcore.identitymanagement/openapi.yml
```openapi
UserName:
      maxLength: 60
      pattern: ^[a-zA-Z0-9._%+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$
      type: string
      format: email
```
Generated ballerina code
```ballerina
public type UserName string;
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Comment by dilanSachi** [comment]
Tested this in update 8.
```
components:
  schemas:
    UserName:
      maxLength: 60
      pattern: ^[a-zA-Z0-9._%+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$
      type: string
      format: email
```
Following is the output.

```bal
@constraint:String {maxLength: 60, pattern: re `^[a-zA-Z0-9._%+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$`}
public type UserName string;
```

Hence this is the expected behaviour, we can close the issue.
