### ISSUE TITLE
Handling OAS Data formats which unsupported from Ballerina in openAPI to Ballerina code generation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#1412]
**Description:**
When an unsupported data format[1] is encountered, the current OpenAPI service, client generations terminates the code generation process and provides an error message indicating the specific reason for the termination. 

- Through this issue, we aim to enhance the code generation behaviour by allowing it to continue running instead of terminating while providing a default data type for the unsupported format.

1. Example for unsupported data types: here number data type only can include 2 data format float, double in [swagger](https://swagger.io/docs/specification/data-models/data-types/#numbers:~:text=Any%20Type.-,Numbers,-OpenAPI%20has%20two) but the user can provide any data format, here the user has provided "currency" format type which is out of standard format type in the number.

```openapi
"valor": {
          "type": "number",
          "format": "currency"
 }
```

**Comment by aneeshafedo** [comment]
This support is already given inBallerina swan lake 2201.6.0 version upwards. We need to handle this in 2201.5.x

**Comment by aneeshafedo** [comment]
Fix was sent to address the unsupported data type format scenarios by priniting a warning message in the CLI without terminating the generation purpose. The `format` would not be considered in generation and the `type` will be used to identify the corresponsing ballerina type.

Ex: 

```yaml
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        price:
          type: number
          format: currency
        name:
          type: string
        tag:
          type: string
        type:
          type: string
        updatedDate:
          type: string
          format: date
      additionalProperties: false
```

**In 2201.5.1 :** 

Generation terminated with the error message 

```
Error occurred when generating service for OpenAPI contract at petstore.yaml. Unsupported OAS data type currency.
```

**Fix :**

Successfully generated with the warning

```
WARNING: unsupported format `currency` will be skipped when generating the counterpart Ballerina type for openAPI schema type: `number```
```

```ballerina
public type Pet record {|
    int id;
    decimal price?;
    string name;
    string tag?;
    string 'type?;
    string updatedDate?;
|};
```

the `price` field is generated in type `decimal` which is the default Ballerina type for the OpenAPI type `number`. The format is ignored here. 

@NipunaRanasinghe @lnash94 Please convey your ideas.
