### ISSUE TITLE
Handle 3.1 OpenAPI schema with multiple types

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#1497]
**Description:**
With OpenAPI 3.1 spec, a schema can have multiple types. This has been initially introduced to handle the `string` and `null` use case but configuring a schema with two or more types is also possible. Please find an approach to address this correctly in OpenAPI client and service generation.

Ex: 

```yaml
schema:
            type:
              - integer
              - string
```
**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
