### ISSUE TITLE
Handle the Enum type in Swagger schema

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/openapi-tools#266]
**Description:**

The `enum` keyword is used to restrict a value to a fixed set of values. It must be an array with at least one element, where each element is unique. 
```
...
JqlQueryClauseTimePredicate:
      required:
        - operand
        - operator
      type: object
      properties:
        operator:
          type: string
          description: The operator between the field and the operand.
          enum:
            - before
            - after
            - from
            - to
            - 'on'
            - during
            - by
```
### Describe solution
Even though we show examples of type string, an enum can be applied to any schema object type.

```ballerina 
public type operator "before" | "after" | "from" | "to" | "on" | "during" | "by";
public type JqlQueryClauseTimePredicate record {
         operator operator;
};
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
