### ISSUE TITLE
Handle when API Key, OAuth 2.0 and Http authentication mechanisms available at the same time

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/openapi-tools#464]
**Description:**
There can be scenarios where both OAuth and API Key authentication have been listed down as security schemas in open-api definition

```
securitySchemes:
    Bearer:
      in: header
      name: Authorization
      type: apiKey
    Client_Credentials:
      description: Client Credentials Flow for ChatBots
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://api.zoom.us/oauth/token
      type: oauth2
    OAuth:
      flows:
        authorizationCode:
          authorizationUrl: https://zoom.us/oauth/authorize
          scopes: {}
          tokenUrl: https://zoom.us/oauth/token
      type: oauth2
```
Need to generate correct client connector for this scenario

**Suggested Labels:**
> client
> improvement

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2-enterprise/choreo/issues/6008

**Comment by Chuhaa** [comment]
https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/dev.to/0.9.7/openapi.yaml
Above specification also has both API Key and OAuth2 in the security schema.
```yml
 securitySchemes:
    api_key:
      in: header
      name: api-key
      type: apiKey
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://dev.to/oauth/authorize
          refreshUrl: https://dev.to/oauth/token
          scopes: {}
          tokenUrl: https://dev.to/oauth/token
        clientCredentials:
          refreshUrl: https://dev.to/oauth/token
          scopes: {}
          tokenUrl: https://dev.to/oauth/token
      type: oauth2
```
