### ISSUE TITLE
Invalid parameter generated for array type  params in openapi

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/openapi-tools#697]
**Description:**
Invalid parameter generated for remote functions when the OpenApi schema provides arrays for request parameters.
#### OpenAPI Specification
```
        - name: petIds
          in: header
          description: The id of the pet to retrieve
          schema:
            type: array
            items:
              type: string
````
#### Generated Code
```ballerina
remote isolated function showPetById([]? petIds = ()) returns Pets|error {   
```
#### Expected Code
```ballerina
remote isolated function showPetById(string[]? petIds = ()) returns Pets|error {   
```

**Steps to reproduce:**
1. Add array type parameter to OpenAPI operation parameter list.
2. Generate the client

**Affected Versions:**
Swan Lake Beta3
**OS, DB, other environment details and versions:**
Ubuntu
