### ISSUE TITLE
Adding `tokenURL` by default into the generated client

### ISSUE THREAD

**Issue by IsuruBoyagane15** [ballerina-platform/openapi-tools#733]
**Description:**
The requirement is to add the `tokenURL` given in the `securitySchemes` (like given below) of the OpenAPI, into the generated client code so that connector consumer will not have to specify it when initializing the client object.

```
"securitySchemes": {
        "oAuth": {
          "type": "oauth2",
          "flows": {
            "clientCredentials": {
              "tokenUrl": "https://apim.preview-dv.choreo.dev:443/oauth2/token",
              "scopes": {}
            }
          }
        }
      }
```

**Describe your problem(s)**

Currently connector consumer have to initalize the client like below,

```
samples13_1:Client c = check new ({
        auth: {
            clientId: "fINUrUtSuNVc6Wrw1AsGacByrooa",
            clientSecret: "xxxx",
            tokenUrl : "https://apim.preview-dv.choreo.dev/oauth2/token"
        }
    });
```

The expectation is to make the `tokenURL` default and let user to initialize the client like below;

```
samples13_1:Client c = check new ({
        auth: {
            clientId: "fINUrUtSuNVc6Wrw1AsGacByrooa",
            clientSecret: "xxxx"
        }
    });
```
The objective is to reduce the number of configs user have to give since the token URL is less changeable value.

Can we have this kind of functionality in the Ballerina OpenAPI tool?

**Suggested Assignees (optional):**
@aneeshafedo

**Comment by LakshanSS** [comment]
@IsuruBoyagane15 
```ballerina
auth: {
}
```
can accept many types of records

Ex: http:OAuth2ClientCredentialsGrantConfig|http:BearerTokenConfig|http:OAuth2RefreshTokenGrantConfig

We give freedom for the user to use any of these options.

But the tokenURL is needed only for `http:OAuth2RefreshTokenGrantConfig`

**Comment by IsuruBoyagane15** [comment]
For the custom connectors generated by choreo-connector-builder service, we currently generate clients that supports only the `http:OAuth2RefreshTokenGrantConfig` authentication config.

Therefore, the users who initialize the client for custom connector that is generated from choreo-connector-builder, has to always give the `tokenURL` when initializing the client. (which is redundant work when using custom connectors generated by the choreo-connector-builder).

This issue intended to have the `tokenURL` added to the client for this specific case. Is there a possibility for that?

**Comment by LakshanSS** [comment]
Please find my design for the solution.

- We have to create our own record for `OAuth2RefreshTokenGrantConfig` instead of using`http:OAuth2RefreshTokenGrantConfig` and add the default value for `refreshUrl` which is taken from the **openapi.yaml**

```ballerina
public type OAuth2RefreshTokenGrantConfig record {|
    string refreshUrl = "https://zoom.us/oauth/token";
    string refreshToken;
    string clientId;
    string clientSecret;
    string[] scopes?;
    decimal defaultTokenExpTime = 3600;
    decimal clockSkew = 0;
    map<string> optionalParams?;
    oauth2:CredentialBearer credentialBearer = oauth2:AUTH_HEADER_BEARER;
    oauth2:ClientConfiguration clientConfig = {};
|};
```
- Since some records are from ballerina oauth module, we need to import `ballerina/oauth` 

```ballerina
import ballerina/oauth2;
```
- Wherever we use `http:OAuth2RefreshTokenGrantConfig`, we have to use `OAuth2RefreshTokenGrantConfig`

### Case 1: (When we expect `ClientConfig` in init function)
<img width="838" alt="ccc" src="https://user-images.githubusercontent.com/32201965/142799479-57095f8d-dda1-4ba2-b4b8-7a5050b2d4ca.png">

### Case2: (When we expect `AuthConfig` in init function)

<img width="859" alt="cdjnf" src="https://user-images.githubusercontent.com/32201965/142800229-eadeb983-fc9f-4af7-a818-f57a54c6da8a.png">

**Comment by aneeshafedo** [comment]
@LakshanSS shall we use record inclusion for `OAuth2RefreshTokenGrantConfig` record ?

```ballerina
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    string refreshUrl = "https://zoom.us/oauth/token";
|};
```

**Comment by LakshanSS** [comment]
> For the custom connectors generated by choreo-connector-builder service, we currently generate clients that supports only the `http:OAuth2RefreshTokenGrantConfig` authentication config.
> 
> Therefore, the users who initialize the client for custom connector that is generated from choreo-connector-builder, has to always give the `tokenURL` when initializing the client. (which is redundant work when using custom connectors generated by the choreo-connector-builder).
> 
> This issue intended to have the `tokenURL` added to the client for this specific case. Is there a possibility for that?

@IsuruBoyagane15 
Is it `OAuth2ClientCredentialsGrantConfig` or `OAuth2RefreshTokenGrantConfig` you use for your requirement?

I guess it is `OAuth2ClientCredentialsGrantConfig` right?

**Comment by LakshanSS** [comment]
@IsuruBoyagane15 
If `OAuth2ClientCredentialsGrantConfig` is your requirement, we will add the following record

```ballerina
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    string tokenUrl = "https://zoom.us/oauth/token";
|};
```

**Comment by aneeshafedo** [comment]
Other than the `tokenUrl` in the  `AuthorizationCode` flow, there are few other fixed values such as `authorizationUrl` and `scopes` that can be found in Open API definition's security schema section.

**ClientCredentials flow**
```yaml
clientCredentials:
          tokenUrl: https://accounts.brex.com/oauth2/v1/token
          scopes:
            openid: openid
            offline_access: offline access
            https://onboarding.brexapis.com/referrals: referrals
```
**Password flow**
```yaml
password: 
          tokenUrl: https://api.getbase.com/oauth2/token
          scopes: 
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only
```
**AuthorizationCode flow**
```yaml
authorizationCode:
          authorizationUrl: https://slack.com/oauth/authorize
          tokenUrl: https://slack.com/api/oauth.access
          scopes:
            users:read: Read user information
            users:write: Modify user information
            im:read: Read messages
            im:write: Write messages
            im:history: Access the message archive
            search:read: Search messages, files, and so on
```
**Implicit flow**
```yaml
implicit:
          authorizationUrl: https://api.getbase.com/oauth2/authorize
          scopes:
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only

```
Shall we provide default values for `tokenUrl`, `scopes`, `authorizationUrl` when found in any of the oauth2 flows ?
@indikasampath2000 @abeykoon @LakshanSS
