### ISSUE TITLE
Default values in Schemas are not supported

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/openapi-tools#923]
**Description:**

A default value can be provided for a given field in a OpenAPI schema as below

```
type:
          description: Certificate configuration type
          type: string 
          enum:
            - NEW_SELF_SIGN_CERTIFICATE
          default: NEW_SELF_SIGN_CERTIFICATE
```

**Generated Record**
```
public type NewCertificateForStation record {
    # Certificate configuration type
    CertificateType 'type;
    # Certificate Common Name
    string commonName;
    # Private key password
    string password;
    # Certificate key length
    int keyLength;
    # Certificate validity in years
    int validity;
    # Organization unit
    string orgUnit?;
    # Organization name
    string orgName?;
    # City
    string city?;
    # State code ISO 3166-1 alpha-2
    string state?;
    # Country code ISO 3166-1 alpha-2
    string country?;
};
```

**Expected record**

```
public type NewCertificateForStation record {
    # Certificate configuration type
    CertificateType 'type = NEW_SELF_SIGN_CERTIFICATE;
    # Certificate Common Name
    string commonName;
    # Private key password
    string password;
    # Certificate key length
    int keyLength;
    # Certificate validity in years
    int validity;
    # Organization unit
    string orgUnit?;
    # Organization name
    string orgName?;
    # City
    string city?;
    # State code ISO 3166-1 alpha-2
    string state?;
    # Country code ISO 3166-1 alpha-2
    string country?;
};
```
